package services

import (
	stdjson "encoding/json"
	"fmt"
	"strings"
	"time"

	"stepbit-app/internal/goals/models"
)

type GoalsService struct{}

func NewGoalsService() *GoalsService {
	return &GoalsService{}
}

func (s *GoalsService) BuildPlan(goal string, rlmEnabled bool) models.GoalPlan {
	goal = strings.TrimSpace(goal)
	if goal == "" {
		goal = "Untitled goal"
	}

	queryPlan := s.buildQueryPlan(goal)
	stages := make([]models.GoalPlanStage, 0, len(queryPlan))
	for idx, stage := range queryPlan {
		config, _ := stage["config"].(map[string]interface{})
		stages = append(stages, models.GoalPlanStage{
			ID:        fmt.Sprintf("stage-%d", idx+1),
			Title:     describeGoalStage(stage["stage_type"], config),
			StageType: fmt.Sprintf("%v", stage["stage_type"]),
			Summary:   summarizeGoalStage(stage["stage_type"], config),
			Config:    config,
		})
	}

	pipeline := map[string]any{
		"name":        "goal_mode_data_pipeline",
		"rlm_enabled": rlmEnabled,
		"stages":      queryPlan,
	}

	return models.GoalPlan{
		PlannerSource: "stepbit-app",
		PlannerMode:   "app_heuristic_v1",
		Goal:          goal,
		PipelineName:  "goal_mode_data_pipeline",
		Summary:       summarizeGoal(goal),
		Notes: []string{
			"This plan is generated by stepbit-app while dedicated planner endpoints are not yet exposed by stepbit-core.",
			"Approve the plan before execution, then inspect evidence, trace, and final synthesis.",
		},
		Stages:   stages,
		Pipeline: pipeline,
	}
}

func (s *GoalsService) BuildReplan(req models.ReplanGoalRequest) models.GoalPlan {
	plan := s.BuildPlan(req.Goal, req.RlmEnabled)
	notes := append([]string{}, plan.Notes...)
	if trimmed := strings.TrimSpace(req.FailureReason); trimmed != "" {
		notes = append(notes, "Replan context: "+trimmed)
	}
	if req.PreviousPlan != nil && len(req.PreviousPlan.Stages) > 0 {
		notes = append(notes, fmt.Sprintf("Previous plan had %d stages; this replan preserves the same goal but refreshes evidence collection.", len(req.PreviousPlan.Stages)))
	}
	plan.Notes = notes
	plan.Summary = "Replanned objective with refreshed evidence collection and execution guidance."
	return plan
}

func (s *GoalsService) BuildPlanFromCore(goal string, rlmEnabled bool, raw map[string]interface{}) models.GoalPlan {
	fallback := s.BuildPlan(goal, rlmEnabled)
	fallback.PlannerSource = "stepbit-core"
	fallback.PlannerMode = "core_http"

	if raw == nil {
		fallback.Notes = append(fallback.Notes, "Core planner returned an empty payload; app fallback shape was used.")
		return fallback
	}

	if summary, ok := raw["summary"].(string); ok && strings.TrimSpace(summary) != "" {
		fallback.Summary = summary
	}
	if plannerMode, ok := raw["planner_mode"].(string); ok && plannerMode != "" {
		fallback.PlannerMode = plannerMode
	}
	if pipelineName, ok := raw["pipeline_name"].(string); ok && pipelineName != "" {
		fallback.PipelineName = pipelineName
	}
	if notes := interfaceSliceToStrings(raw["notes"]); len(notes) > 0 {
		fallback.Notes = notes
	}
	if pipeline, ok := raw["pipeline"].(map[string]interface{}); ok && len(pipeline) > 0 {
		fallback.Pipeline = pipeline
	}
	if stages := s.extractGoalStages(raw["stages"]); len(stages) > 0 {
		fallback.Stages = stages
	}

	return fallback
}

func (s *GoalsService) BuildExecutionPayload(req models.ExecuteGoalRequest) map[string]interface{} {
	goal := strings.TrimSpace(req.Goal)
	plan := req.Plan
	if plan == nil {
		generated := s.BuildPlan(goal, req.RlmEnabled)
		plan = &generated
	}

	return map[string]interface{}{
		"question":    goal,
		"rlm_enabled": req.RlmEnabled,
		"pipeline":    plan.Pipeline,
	}
}

func (s *GoalsService) BuildSynthesisPrompt(goal string, pipelineResult map[string]interface{}) string {
	goal = strings.TrimSpace(goal)
	dataJSON := "{}"
	if pipelineResult != nil {
		if intermediate, ok := pipelineResult["intermediate_results"]; ok {
			dataJSON = toJSONString(intermediate)
		} else {
			dataJSON = toJSONString(pipelineResult)
		}
	}

	return strings.TrimSpace(fmt.Sprintf(
		`You are Stepbit Goal Mode.

The user asked you to complete this objective:
%s

You have structured data collected from the Stepbit application database and automation history.
Use only the evidence present in that data. If the available data is not enough to fully answer the goal, say so clearly.

Return a concise, useful response with these sections:
Summary
Evidence
Next Steps

Collected data (JSON):
%s`, goal, dataJSON))
}

func (s *GoalsService) buildQueryPlan(goal string) []map[string]interface{} {
	normalized := strings.ToLower(strings.TrimSpace(goal))
	queries := make([]string, 0, 2)

	switch {
	case containsAny(normalized, "message", "chat", "conversation"):
		queries = append(queries,
			"SELECT session_id, role, model, created_at, LEFT(content, 240) AS content_preview FROM messages ORDER BY created_at DESC LIMIT 12",
			"SELECT id, title, created_at, updated_at FROM sessions ORDER BY updated_at DESC LIMIT 8",
		)
	case containsAny(normalized, "skill", "skills", "prompt", "template"):
		queries = append(queries,
			"SELECT name, tags, updated_at, LEFT(content, 240) AS content_preview FROM skills ORDER BY updated_at DESC LIMIT 12",
		)
	case containsAny(normalized, "pipeline", "workflow"):
		queries = append(queries,
			"SELECT name, updated_at, definition FROM pipelines ORDER BY updated_at DESC LIMIT 8",
			"SELECT source_id, action_type, status, created_at, completed_at, error FROM execution_runs WHERE source_type = 'pipeline' ORDER BY created_at DESC LIMIT 12",
		)
	case containsAny(normalized, "failure", "failures", "error", "errors", "execution", "executions", "job", "jobs", "trigger", "triggers", "scheduled", "schedule", "cron"):
		queries = append(queries,
			"SELECT source_type, source_id, action_type, status, created_at, completed_at, error FROM execution_runs ORDER BY created_at DESC LIMIT 20",
		)
	default:
		queries = append(queries,
			"SELECT id, title, created_at, updated_at FROM sessions ORDER BY updated_at DESC LIMIT 8",
			"SELECT source_type, source_id, action_type, status, created_at, completed_at, error FROM execution_runs ORDER BY created_at DESC LIMIT 12",
		)
	}

	stages := make([]map[string]interface{}, 0, len(queries)+1)
	for _, query := range queries {
		stages = append(stages, map[string]interface{}{
			"stage_type": "mcp_tool_stage",
			"config": map[string]interface{}{
				"tool": "duckdb_query",
				"input": map[string]interface{}{
					"query": query,
				},
			},
		})
	}

	stages = append(stages, map[string]interface{}{
		"stage_type": "verification_stage",
		"config": map[string]interface{}{
			"description": "Verify that the goal pipeline returned application data for analysis.",
		},
	})

	return stages
}

func summarizeGoal(goal string) string {
	normalized := strings.ToLower(strings.TrimSpace(goal))

	switch {
	case containsAny(normalized, "failure", "failures", "error", "errors"):
		return "Investigate failures with execution history, recent runs, and targeted verification."
	case containsAny(normalized, "pipeline", "workflow"):
		return "Inspect pipeline definitions, recent executions, and operational evidence."
	case containsAny(normalized, "skill", "prompt", "template"):
		return "Review reusable prompt assets and their latest changes."
	case containsAny(normalized, "message", "chat", "conversation"):
		return "Analyze recent conversations and session activity with supporting evidence."
	default:
		return "Collect evidence from Stepbit app data, verify relevance, and draft a grounded final answer."
	}
}

func describeGoalStage(stageType interface{}, config map[string]interface{}) string {
	stageTypeStr := fmt.Sprintf("%v", stageType)
	switch stageTypeStr {
	case "mcp_tool_stage":
		if tool, ok := config["tool"].(string); ok && tool != "" {
			return fmt.Sprintf("Collect data with %s", tool)
		}
		return "Collect supporting data"
	case "verification_stage":
		return "Verify collected evidence"
	default:
		return stageTypeStr
	}
}

func summarizeGoalStage(stageType interface{}, config map[string]interface{}) string {
	stageTypeStr := fmt.Sprintf("%v", stageType)
	switch stageTypeStr {
	case "mcp_tool_stage":
		if input, ok := config["input"].(map[string]interface{}); ok {
			if query, ok := input["query"].(string); ok && query != "" {
				return fmt.Sprintf("Run structured evidence query: %s", query)
			}
		}
		return "Execute an MCP tool call to gather evidence."
	case "verification_stage":
		if description, ok := config["description"].(string); ok && description != "" {
			return description
		}
		return "Verify that the pipeline returned enough application data."
	default:
		return "Execute the configured stage."
	}
}

func (s *GoalsService) extractGoalStages(value interface{}) []models.GoalPlanStage {
	rawStages := interfaceSlice(value)
	stages := make([]models.GoalPlanStage, 0, len(rawStages))
	for idx, rawStage := range rawStages {
		stageMap, _ := rawStage.(map[string]interface{})
		config, _ := stageMap["config"].(map[string]interface{})
		stageType := fmt.Sprintf("%v", stageMap["stage_type"])
		if stageType == "" || stageType == "<nil>" {
			stageType = "planner_stage"
		}
		title := describeGoalStage(stageType, config)
		if explicitTitle, ok := stageMap["title"].(string); ok && strings.TrimSpace(explicitTitle) != "" {
			title = explicitTitle
		}
		summary := summarizeGoalStage(stageType, config)
		if explicitSummary, ok := stageMap["summary"].(string); ok && strings.TrimSpace(explicitSummary) != "" {
			summary = explicitSummary
		}
		stageID := fmt.Sprintf("stage-%d", idx+1)
		if explicitID, ok := stageMap["id"].(string); ok && strings.TrimSpace(explicitID) != "" {
			stageID = explicitID
		}

		stages = append(stages, models.GoalPlanStage{
			ID:        stageID,
			Title:     title,
			StageType: stageType,
			Summary:   summary,
			Config:    config,
		})
	}
	return stages
}

func containsAny(input string, terms ...string) bool {
	for _, term := range terms {
		if strings.Contains(input, term) {
			return true
		}
	}
	return false
}

func toJSONString(value interface{}) string {
	if value == nil {
		return "null"
	}

	bytes, err := stdjson.MarshalIndent(value, "", "  ")
	if err != nil {
		return fmt.Sprintf("%v", value)
	}

	return string(bytes)
}

func interfaceSliceToStrings(value interface{}) []string {
	items := interfaceSlice(value)
	out := make([]string, 0, len(items))
	for _, item := range items {
		out = append(out, fmt.Sprintf("%v", item))
	}
	return out
}

func interfaceSlice(value interface{}) []interface{} {
	switch typed := value.(type) {
	case []interface{}:
		return typed
	case []map[string]interface{}:
		out := make([]interface{}, 0, len(typed))
		for _, item := range typed {
			out = append(out, item)
		}
		return out
	default:
		return []interface{}{}
	}
}

func (s *GoalsService) BuildSourceID(goal string) string {
	trimmed := strings.Join(strings.Fields(goal), " ")
	if trimmed == "" {
		return fmt.Sprintf("goal-%d", time.Now().Unix())
	}

	if len(trimmed) > 96 {
		return trimmed[:96]
	}

	return trimmed
}
