package handlers

import (
	"context"
	"errors"
	"stepbit-app/internal/core"
	executionServices "stepbit-app/internal/execution/services"
	"stepbit-app/internal/goals/models"
	"stepbit-app/internal/goals/services"
	"strings"

	"github.com/gofiber/fiber/v2"
)

type GoalsHandler struct {
	goalsService     *services.GoalsService
	executionService *executionServices.ExecutionService
	coreClient       *core.StepbitCoreClient
}

func NewGoalsHandler(goalsService *services.GoalsService, executionService *executionServices.ExecutionService, coreClient *core.StepbitCoreClient) *GoalsHandler {
	return &GoalsHandler{
		goalsService:     goalsService,
		executionService: executionService,
		coreClient:       coreClient,
	}
}

func (h *GoalsHandler) PlanGoal(c *fiber.Ctx) error {
	var req models.PlanGoalRequest
	if err := c.BodyParser(&req); err != nil {
		return c.Status(fiber.StatusBadRequest).JSON(fiber.Map{"error": err.Error()})
	}

	if strings.TrimSpace(req.Goal) == "" {
		return c.Status(fiber.StatusBadRequest).JSON(fiber.Map{"error": "goal is required"})
	}

	plan := h.goalsService.BuildPlan(req.Goal, req.RlmEnabled)
	plannerBackend := "stepbit-app"
	if raw, err := h.coreClient.PlanGoal(c.Context(), fiber.Map{
		"goal":        req.Goal,
		"rlm_enabled": req.RlmEnabled,
	}); err == nil {
		plan = h.goalsService.BuildPlanFromCore(req.Goal, req.RlmEnabled, raw)
		plannerBackend = "stepbit-core"
	} else if err != nil && !errors.Is(err, core.ErrPlannerEndpointsUnavailable) {
		plan.Notes = append(plan.Notes, "Core planner attempt failed; app fallback used: "+err.Error())
	}

	if runID, err := h.executionService.InsertRun("goal", h.goalsService.BuildSourceID(req.Goal), "plan_goal", req); err == nil {
		_ = h.executionService.CompleteRun(runID, "completed", fiber.Map{"plan": plan, "planner_backend": plannerBackend}, nil)
	}

	return c.JSON(fiber.Map{"plan": plan, "planner_backend": plannerBackend})
}

func (h *GoalsHandler) ReplanGoal(c *fiber.Ctx) error {
	var req models.ReplanGoalRequest
	if err := c.BodyParser(&req); err != nil {
		return c.Status(fiber.StatusBadRequest).JSON(fiber.Map{"error": err.Error()})
	}

	if strings.TrimSpace(req.Goal) == "" {
		return c.Status(fiber.StatusBadRequest).JSON(fiber.Map{"error": "goal is required"})
	}

	plan := h.goalsService.BuildReplan(req)
	plannerBackend := "stepbit-app"
	if raw, err := h.coreClient.ReplanGoal(c.Context(), fiber.Map{
		"goal":           req.Goal,
		"rlm_enabled":    req.RlmEnabled,
		"failure_reason": req.FailureReason,
		"previous_plan":  req.PreviousPlan,
		"last_result":    req.LastResult,
	}); err == nil {
		plan = h.goalsService.BuildPlanFromCore(req.Goal, req.RlmEnabled, raw)
		plan.Notes = append(plan.Notes, "Replan generated by stepbit-core HTTP planner endpoint.")
		plannerBackend = "stepbit-core"
	} else if err != nil && !errors.Is(err, core.ErrPlannerEndpointsUnavailable) {
		plan.Notes = append(plan.Notes, "Core replan attempt failed; app fallback used: "+err.Error())
	}

	if runID, err := h.executionService.InsertRun("goal", h.goalsService.BuildSourceID(req.Goal), "replan_goal", req); err == nil {
		_ = h.executionService.CompleteRun(runID, "completed", fiber.Map{"plan": plan, "planner_backend": plannerBackend}, nil)
	}

	return c.JSON(fiber.Map{"plan": plan, "planner_backend": plannerBackend})
}

func (h *GoalsHandler) ExecuteGoal(c *fiber.Ctx) error {
	var req models.ExecuteGoalRequest
	if err := c.BodyParser(&req); err != nil {
		return c.Status(fiber.StatusBadRequest).JSON(fiber.Map{"error": err.Error()})
	}

	if strings.TrimSpace(req.Goal) == "" {
		return c.Status(fiber.StatusBadRequest).JSON(fiber.Map{"error": "goal is required"})
	}

	plan := req.Plan
	if plan == nil {
		generated := h.goalsService.BuildPlan(req.Goal, req.RlmEnabled)
		if raw, err := h.coreClient.PlanGoal(c.Context(), fiber.Map{
			"goal":        req.Goal,
			"rlm_enabled": req.RlmEnabled,
		}); err == nil {
			generated = h.goalsService.BuildPlanFromCore(req.Goal, req.RlmEnabled, raw)
		} else if err != nil && !errors.Is(err, core.ErrPlannerEndpointsUnavailable) {
			generated.Notes = append(generated.Notes, "Core planner attempt failed during execute; app fallback used: "+err.Error())
		}
		plan = &generated
		req.Plan = &generated
	}

	execPayload := h.goalsService.BuildExecutionPayload(req)
	sourceID := h.goalsService.BuildSourceID(req.Goal)

	runID, runInsertErr := h.executionService.InsertRun("goal", sourceID, "execute_goal", execPayload)
	result, err := h.coreClient.ExecutePipeline(c.Context(), execPayload)
	if err == nil {
		prompt := h.goalsService.BuildSynthesisPrompt(req.Goal, result)
		finalAnswer, completionErr := h.coreClient.ChatCompletion(context.Background(), []core.Message{
			{
				Role:    "system",
				Content: "You are a concise Stepbit operations analyst. Ground your answer in the supplied data, acknowledge uncertainty, and keep the structure easy to scan.",
			},
			{
				Role:    "user",
				Content: prompt,
			},
		}, core.ChatOptions{
			Stream: false,
		})
		if completionErr == nil && finalAnswer != "" {
			result["final_answer"] = finalAnswer

			trace, _ := result["trace"].([]interface{})
			trace = append(trace, "GoalMode: final answer drafted via chat completions")
			result["trace"] = trace
		}
	}
	result = core.NormalizeExecutionResult(result, execPayload["pipeline"])
	if runInsertErr == nil {
		status := "completed"
		if err != nil {
			status = "failed"
		}
		_ = h.executionService.CompleteRun(runID, status, result, err)
	}
	if err != nil {
		return c.Status(fiber.StatusBadGateway).JSON(fiber.Map{"error": err.Error()})
	}

	return c.JSON(fiber.Map{
		"goal":     req.Goal,
		"plan":     plan,
		"pipeline": execPayload["pipeline"],
		"result":   result,
	})
}
